name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/foamdino/vouch-proxy

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/vouch-proxy/go

#     - name: Get dependencies
#       run: |
#         go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#             dep ensure
#         fi
    - name: Get
      run: |
        pwd
        ls -la /home/runner/work/vouch-proxy/vouch-proxy/go/src/github.com/foamdino/vouch-proxy
        /home/runner/work/vouch-proxy/vouch-proxy/go/src/github.com/foamdino/vouch-proxy/do.sh goget
      env:
        GOPATH: /home/runner/work/vouch-proxy/go

#     - name: Build
#       run: go build -v .

    - name: Build
      run: |
        /home/runner/work/vouch-proxy/vouch-proxy/go/src/github.com/foamdino/vouch-proxy/do.sh build
      env:
        GOPATH: /home/runner/work/vouch-proxy/go
      
